TRAIN = "TRAIN"
TEST = "TEST"
OFF_TARGET = "OFF_TARGET"
OFF_AVAILABLE_NUMS = "OFF_AVAILABLE_NUMS"
OFF_POSITIVE_NUMBERS = "OFF_POSITIVE_NUMBERS"
OFF_SIX_AVAILABLE = "OFF_SIX_AVAILABLE"
OFF_SEVEN_AVAILABLE = "OFF_SEVEN_AVAILABLE"
OFF_EIGHT_AVAILABLE = "OFF_EIGHT_AVAILABLE"


DATA_SOURCE = "1a3orn_countdown"